### ISSUE TITLE
Doesn't inject anything in Anki 2.1.20beta6

### ISSUE THREAD

**Issue by khonkhortisan** [zacharied/anki-content-injector#2]
[info] https://anki.tenderapp.com/discussions/beta-testing/1708-anki-2120-beta
different hooks: https://github.com/ankitects/anki-addons/blob/master/demos/porting_clickable_tags/__init__.py#L101

**Comment by zacharied** [comment]
Thanks for the link. Will try to get this within the week.

**Comment by khonkhortisan** [comment]
works again in Anki 2.1.21beta2
