### ISSUE TITLE
Is there any way to make this work on mobile?

### ISSUE THREAD

**Issue by jamesnelmore** [zacharied/anki-content-injector#3]
If not the HTML and js, just the css?

**Comment by khonkhortisan** [comment]
add `@import url(_myfile.css);` to the top of the styling of every last note type

**Comment by zacharied** [comment]
Mobile plugins use a completely separate API from desktop Anki and are out of the scope of this project. Manually importing the styling in the note type as described by @khonkhortisan is the best way to achieve this.
